### ISSUE TITLE
Glean probe-scraper failure

### ISSUE THREAD

**Issue by mcarare** [mozilla/probe-scraper#457]
Task fails with 

```
Error: could not handle the request
The requested URL returned error: 500
```

Example [PR](https://github.com/mozilla-mobile/android-components/runs/7278007087?check_suite_focus=true#step:2:15).

**Comment by Dexterp37** [comment]
@rafrombrc with @relud not around, do you know who could help with this?

**Comment by scholtzan** [comment]
I was able to access the traceback:

```
Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 99, in view_func return function(request._get_current_object()) File "/workspace/probe_scraper/glean_push.py", line 43, in main updated_paths = runner.main( File "/workspace/probe_scraper/runner.py", line 639, in main upload_paths += load_glean_metrics( File "/workspace/probe_scraper/runner.py", line 540, in load_glean_metrics send_ses( File "/workspace/probe_scraper/emailer.py", line 39, in send_ses with open(EMAIL_FILE, "a") as f: OSError: [Errno 30] Read-only file system: 'emails.txt'
```

The cloud function tries to write some emails to the `email.txt` file but has only read access. Generally, afaik cloud functions can only write to files if they are in `tmp/`, but this one is configured as just `email.txt`. 
The cloud function is in a sandbox project that can only be edited by relud or SRE.
